--CRIAR BANCO DE DADOS
CREATE DATABASE JOTAPE

--COLOCAR O BANCO EM USO 
USE JOTAPE

--CRIAR TABELA
CREATE TABLE AMIGO
(NM_AMIGO VARCHAR(50) NOT NULL,
DT_NASCIMENTO DATE NOT NULL,
NR_TELEFONE INT NULL,
DS_EMAIL VARCHAR(80) NULL)

--CONSULTAR TUDO
SELECT * FROM AMIGO

--INSERIR DADOS
INSERT INTO AMIGO VALUES ('ADEMIR','29/11/1987',984787949,'ademilsondsad@yahoo.com')

--INSERIR DADOS COM COMPOS ESPECIFICOS
INSERT INTO AMIGO (DT_NASCIMENTO,NM_AMIGO)
VALUES ('20/10/2020','JERFISSON')

--INSERIR DADOS ESPECIFICANDO ONDE NEGATIVOS
INSERT INTO AMIGO VALUES ('PEDRO','03/12/2002',NULL,NULL)
--INSERT INTO AMIGO VALUES ('PEDRA','30/02/1999',NULL,NULL)

--SELECIONA TODOS ONDE O NM_AMIGO FOR IGUAL A PEDRO
SELECT * FROM AMIGO WHERE NM_AMIGO = 'PEDRO'
