CREATE DATABASE LOJA_3

USE LOJA_3

CREATE TABLE PRODUTOS_3(
CD_PRODUTO INT IDENTITY(1,1) NOT NULL,
NM_PRODUTO VARCHAR(80) NOT NULL,
QT_ESTOQUE INT NOT NULL,
VL_PRECO NUMERIC(18,2) NOT NULL,
QT_MINIMA INT NOT NULL
CONSTRAINT PK_CODIGO PRIMARY KEY(CD_PRODUTO), 
CONSTRAINT UNICO_NOME UNIQUE(NM_PRODUTO) 
)

--INCLUIR UM CAMPO APOS A CRIAÇÃO DA TABELA
--ALTERAR A ESTRUTURA DA TABELA
ALTER TABLE PRODUTOS_3 ADD UNIDADE VARCHAR(10) NULL

--INCLUIR UMA COLUNBA CHAMADA DESCONTO
ALTER TABLE PRODUTOS_3 ADD DESCONTO NUMERIC(4,2) NULL

INSERT INTO PRODUTOS_3 VALUES
('AREIA FINA', 1000, 59.90, 200,'M³',0.1),
('AREIA MEDIA',550, 70, 150, 'M³',0.1)

SELECT * FROM PRODUTOS_3

INSERT INTO PRODUTOS_3 VALUES
('CIMENTO', 500, 900, 1000, 'SACOS', 0.05)

--ALTERAR A ESTRUTURA DA TABELA INCLUINDO O CAMPO NM_FORNECEDOR
ALTER TABLE PRODUTOS_3 ADD NM_FORNECEDOR VARCHAR(80) NULL

--ALTERAR/INSERIR OS DADOS DA COLUNA FORNECEDOR
UPDATE PRODUTOS_3
SET NM_FORNECEDOR = 'PORTLAND'
WHERE NM_PRODUTO = 'CIMENTO'

UPDATE PRODUTOS_3
SET NM_FORNECEDOR = 'AREIAS MIL'
WHERE NM_PRODUTO LIKE 'AREIA%'