CREATE DATABASE FMU_ALUNO
USE FMU_ALUNO

CREATE TABLE CURSO(
CD_CURSO INT IDENTITY (1,1) NOT NULL,
NM_CURSO VARCHAR(50) NOT NULL,
CONSTRAINT PK_CURSO PRIMARY KEY (CD_CURSO),
CONSTRAINT UNICO_CURSO UNIQUE (NM_CURSO))

CREATE TABLE TURMA
(CD_TURMA INT IDENTITY(1,1) NOT NULL,
NM_TURMA VARCHAR(10) NOT NULL,
NR_ANO_LETIVO INT NOT NULL,
NR_SEMESTRE_LETIVO INT NOT NULL,
CD_CURSO INT NOT NULL,
CONSTRAINT PK_TURMA PRIMARY KEY(CD_TURMA),
CONSTRAINT FK_TURMA FOREIGN KEY(CD_CURSO) REFERENCES
CURSO(CD_CURSO),
CONSTRAINT CHEQUE_SEMESTRE CHECK (NR_SEMESTRE_LETIVO IN (1,2)))

CREATE TABLE ALUNO
(CD_ALUNO INT IDENTITY(1,1) NOT NULL,
NR_RA INT NOT NULL,
NM_ALUNO VARCHAR(50) NOT NULL,
CD_TURMA INT NOT NULL,
CONSTRAINT PK_ALUNO PRIMARY KEY(CD_ALUNO),
CONSTRAINT FK_ALUNO FOREIGN KEY(CD_TURMA) REFERENCES
TURMA(CD_TURMA),
CONSTRAINT UNICO_RA UNIQUE(NR_RA))

INSERT INTO CURSO VALUES('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS-ADS')
INSERT INTO CURSO VALUES('JOGOS DIGITAIS-JOGOS')

SELECT * FROM CURSO

INSERT INTO TURMA VALUES ('173202A16',2024,1,1)
INSERT INTO TURMA VALUES ('173202B16',2024,1,2)
INSERT INTO TURMA VALUES ('228104A05',2024,1,1)